#!/usr/bin/env python
import sys

from config.env import getenv

vars = [
    "DATABASE_URL",
    "DJANGO_SECRET_KEY",
    "DJANGO_ADMIN_URL",
    "DJANGO_ALLOWED_HOSTS",
    "CORS_ALLOWED_ORIGINS",
    "PLUNK_API_KEY",
    "PLUNK_API_URL",
    "FRONTEND_URL",
    "FRONTEND_DOMAIN",
    "FRONTEND_PROTOCOL",
    "LINKEDIN_OPENIDCONNECT_KEY",
    "LINKEDIN_OPENIDCONNECT_SECRET",
    "GOOGLE_OAUTH2_KEY",
    "GOOGLE_OAUTH2_SECRET",
    "TWITTER_OAUTH2_KEY",
    "TWITTER_OAUTH2_SECRET",
    # Backblaze creds
    "BACKBLAZE_APP_KEY_ID",
    "BACKBLAZE_APP_KEY",
    "BACKBLAZE_BUCKET",
    # JWT
    "ACCESS_TOKEN_LIFETIME",
    "REFRESH_TOKEN_LIFETIME",
]


def main():
    from config.settings import load_dotenv_files

    args = sys.argv[1:]
    if not args:
        print("usage: exportenv <filename>")
        sys.exit(1)

    load_dotenv_files("production")
    with open(args[0], "w") as f:
        f.write("DJANGO_ENV='production'\n")
        for var in vars:
            value = getenv(var)
            f.write(f'{var}="{value}"\n')


if __name__ == "__main__":
    main()
